modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/dragon-forge/BotanicAdditions/issues"
license = "All rights reserved"

[[mods]]
modId = "botanicadds"
version = "${file.jarVersion}"
displayName = "Botanic Additions"
updateJSONURL = "https://api.modrinth.com/updates/2u3eevWi/forge_updates.json"
displayURL = "https://h.zeith.org/api/fmlhp/310637"
logoFile = "icon.png"
authors = "Zeitheron"

description = '''
Implementing handy features for Botania!
'''

[[dependencies.botanicadds]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE" # NONE/BEFORE/AFTER
side = "BOTH"

[[dependencies.botanicadds]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"

[[dependencies.botanicadds]]
modId = "hammerlib"
mandatory = true
versionRange = "[19.3.57,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.botanicadds]]
modId = "botania"
mandatory = true
versionRange = "[1.19.2-440-FORGE,)"
ordering = "AFTER"
side = "BOTH"
